function set_plot_settings(mode)
    

    if mode == 'publication'

        %     axesFontName = 'factory';
        axesFontName = 'Helvetica';
        %     axesFontName = 'Times New Roman';
        %     set(0,'Defaultfigureposition',[0 100 800 800], ...
        %         'Defaulttextinterpreter','latex', ...
        %         'DefaultAxesFontName', axesFontName, ...
        %         'DefaultTextFontName', axesFontName, ...
        %         'DefaultAxesFontSize', 'default', ...
        %         'DefaultTextFontSize', 'default', ...
        %         'Defaultuicontrolfontweight','bold', ...
        %         'Defaulttextfontweight','bold', ...
        %         'Defaultaxesfontweight','bold');

        set(0, ...
        'Defaulttextinterpreter','latex', ...
        'DefaultAxesFontName', axesFontName, ...
        'DefaultTextFontName', axesFontName, ...
        'DefaultAxesFontSize', 12, ...
        'DefaultTextFontSize', 12, ...
        'DefaultAxesLabelFontSize', 2.0, ...
        'Defaultuicontrolfontweight','default', ...
        'Defaulttextfontweight','default', ...
        'Defaultaxesfontweight','default');
    
        ax = gca;
        
    end
    
    

end